# yaml-language-server: $schema=https://aka.ms/dsc/schemas/v3/bundled/config/document.json
$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
  - name: k3d
    type: BrookeHamilton.Setup/K3d
    properties:
      _exist: true
